services:
  backend:
    build:
      context: ./legal-rat-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./legal-rat-backend:/app

  frontend:
    build:
      context: ./legal-rat-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./legal-rat-frontend:/app
      - /app/node_modules
